### ISSUE TITLE
Memory and CPU usage too high

### ISSUE THREAD

**Issue by burakozhan** [sensorberg-dev/windows10-sdk#2]
High memory usage. 
High CPU usage. 

Possibly a memory leak causes extremely high memory usage that increases while runinning the Showcase app for a short while.  
~5 GB in ~90 Minutes is not an acceptable memory consumption. 
Also around 25% CPU is used all of the time. 

![memory usage win 10](https://cloud.githubusercontent.com/assets/7325233/8803254/3782aa5a-2fc6-11e5-9c6a-14ceb8fd1aed.PNG)

**Comment by burakozhan** [comment]
Repeating test with more beacons around increases CPU load.

**Comment by burakozhan** [comment]
PRoblem seems to be limited to the Showcase app and not within the SDK.

**Comment by EagleEyeBW** [comment]
the current versions have many fixes and this should be fixed
